name: checkov-check

on:
  push:
    branches:
      - 'tech-dev-*'

permissions:
  contents: read

jobs:
  checkov-check:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          set -e  # Exit on any non-zero exit code
          echo "Installing urllib3 and requests..."
          pip install -q -U urllib3 requests
          echo "Installing Checkov..."
          pip install -q checkov

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Checkov scan
        run: |
          set -e
          echo "Running Checkov scan..."
          checkov --config-file $GITHUB_WORKSPACE/CodeValidation/checkov-check.yml --directory $GITHUB_WORKSPACE > checkov_output.log 2>&1
          if [ $? -ne 0 ]; then
            echo "Checkov scan failed. See checkov_output.log for details"
            exit 1
          fi

      - name: Terraform Apply (Conditional)  # Consider separating to a different workflow
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          set -e
          echo "Applying Terraform changes..."
          terraform apply -auto-approve plan.out > terraform_apply_output.log 2>&1
          if [ $? -ne 0 ]; then
            echo "Terraform Apply failed. See terraform_apply_output.log for details"
            exit 1
          fi
