name: Terraform

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Install tflint
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
          if [ $? -ne 0 ]; then exit 1; fi

      - name: Run tflint
        run: |
          tflint
          if [ $? -ne 0 ]; then exit 1; fi

      - name: Install tfsec
        run: |
          curl -sL https://github.com/aquasecurity/tfsec/releases/latest/download/tfsec-linux-amd64 -o tfsec
          chmod +x tfsec
          sudo mv tfsec /usr/local/bin/
          if [ $? -ne 0 ]; then exit 1; fi

      - name: Run tfsec
        run: |
          tfsec .
          if [ $? -ne 0 ]; then exit 1; fi

      - name: Install Checkov
        run: |
          pip install checkov
          if [ $? -ne 0 ]; then exit 1; fi

      - name: Run Checkov
        run: |
          checkov -d .
          if [ $? -ne 0 ]; then exit 1; fi

      - name: Install Terrascan
        run: |
          curl -LJO https://github.com/accurics/terrascan/releases/latest/download/terrascan-Linux-x86_64
          chmod +x terrascan-Linux-x86_64
          sudo mv terrascan-Linux-x86_64 /usr/local/bin/terrascan
          if [ $? -ne 0 ]; then exit 1; fi

      - name: Run Terrascan
        run: |
          terrascan scan -d .
          if [ $? -ne 0 ]; then exit 1; fi

      - name: Install terraform-compliance
        run: |
          pip install terraform-compliance
          if [ $? -ne 0 ]; then exit 1; fi

      - name: Run terraform-compliance
        run: |
          terraform-compliance -p plan.out -f compliance/
          if [ $? -ne 0 ]; then exit 1; fi

      - name: Generate Terraform Plan
        id: plan
        run: |
          terraform plan -out=plan.out
          if [ $? -ne 0 ]; then exit 1; fi

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          terraform apply -auto-approve plan.out
          if [ $? -ne 0 ]; then exit 1; fi

