name: terraform-checks

on:
  push:
    branches:
      - 'tech-dev-*'

permissions:
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Terraform Init
        run: |
          set -e
          echo "Running terraform init..."
          terraform init
          echo "Terraform init completed successfully."

      - name: Terraform Validate
        run: |
          set -e
          echo "Running terraform validate..."
          terraform validate
          echo "Terraform validate completed successfully."

      - name: Generate Terraform Plan
        id: plan
        run: |
          set -e
          echo "Generating Terraform Plan..."
          terraform plan -out=plan.out
          echo "Terraform plan generated successfully."

      - name: Install tflint
        run: |
          set -e
          echo "Installing tflint..."
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
          echo "tflint installed successfully."

      - name: Run tflint
        run: |
          set -e
          echo "Running tflint..."
          tflint
          echo "tflint completed successfully."

      - name: Install tfsec
        run: |
          set -e
          echo "Installing tfsec..."
          curl -sL https://github.com/aquasecurity/tfsec/releases/latest/download/tfsec-linux-amd64 -o tfsec
          chmod +x tfsec
          sudo mv tfsec /usr/local/bin/
          echo "tfsec installed successfully."

      - name: Run tfsec
        run: |
          set -e
          echo "Running tfsec..."
          tfsec .
          echo "tfsec completed successfully."

      - name: Install Checkov
        run: |
          set -e
          echo "Installing Checkov..."
          pip install checkov
          echo "Checkov installed successfully."

      - name: Run Checkov
        run: |
          set -e
          echo "Running Checkov..."
          checkov -d .
          echo "Checkov completed successfully."

      - name: Run Terrascan
        run: |
          set -e
          echo "Running Terrascan..."
          terrascan scan -d .
          echo "Terrascan completed successfully."

      - name: Terraform Apply (Conditional)
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          set -e
          echo "Applying Terraform changes..."
          terraform apply -auto-approve plan.out
          echo "Terraform apply completed successfully."

