
name: checkov-check

on:
  push:
    branches:
      - 'tech-dev-*'

permissions: 
  contents: read

jobs:
  checkov-check:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          echo "Installing urllib3 and requests..."
          pip install -q -U urllib3 requests
          if [ $? -ne 0 ]; then
            echo "Failed to install urllib3 and requests"
            exit 1
          fi
          echo "Installing Checkov..."
          pip install -q checkov
          if [ $? -ne 0 ]; then
            echo "Failed to install Checkov"
            exit 1
          fi

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Checkov scan
        run: |
          echo "Running Checkov scan..."
          checkov --config-file $GITHUB_WORKSPACE/CodeValidation/checkov-check.yml --directory $GITHUB_WORKSPACE
          if [ $? -ne 0 ]; then
            echo "Checkov scan failed"
            exit 1
          fi

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          echo "Applying Terraform changes..."
          terraform apply -auto-approve plan.out
          if [ $? -ne 0 ]; then
            echo "Terraform Apply failed"
            exit 1
          fi
